### PR TITLE
fix: #78 updated woql schema

### LINKED ISSUE #78: Update for WOQL schema changes
The document query elements are probably no longer correct. We need to update to reflect the current schema:

```js

WOQLQuery.prototype.read_object = function(IRI, OutputVar, Format) {
    //if (IRI && IRI == 'args') return ['document_uri', 'document']
    if (this.cursor['@type']) this.wrapCursorWithAnd()
    this.cursor['@type'] = 'ReadObject'
    this.cursor['document_uri'] = this.expandValueVariable(IRI)
    this.cursor['document'] = this.expandValueVariable(OutputVar)
    return this.wform(Format)
}

```
Current schema:

```js
{ "@id" : "ReadDocument",
  "@type" : "Class",
  "@documentation" : {
      "@comment" : "Read a full document from an identifier.",
      "@properties" : { "document" : "Variable which will be bound to the document.",
                        "identifier" : "The URI of the document to load."
                      }
  },
  "@key" : { "@type" : "ValueHash" },
  "@inherits" : "Query",
  "document" : "DataValue",
  "identifier" : "NodeValue" }
```

### PR DESCRIPTION
**Pull request by Neelterminusdb**
fixes #78 #75 

Signed-off-by: NeelParihar <neel@terminusdb.com>

### CODE REVIEW

**Comment by Neelterminusdb** [comment]
> You can probably just delete the commented code.
> 
> We should add `DeleteDocument` and `UpdateDocument` as well - I can help if you have any questions.

Oh okay will do that and let you know if i need anything

**Comment by spl** [comment]
> Should is keep the name of the functions as delete_document or delete_objects

Can you create new names and keep the old ones for backwards-compatibility? The new ones should have the documentation (if there is any), but the old ones don't need to go.

**Comment by spl** [comment]
Would this work?

```js
WOQLQuery.prototype.read_document = function ... {
  ...
}

WOQLQuery.prototype.read_object = WOQLQuery.prototype.read_document
```

**Comment by Neelterminusdb** [comment]
I dont think there is already a function for delete document and and update document, so i dont think it will create any type of problem

**Comment by Neelterminusdb** [comment]
> Would this work?
> 
> ```js
> WOQLQuery.prototype.read_document = function ... {
>   ...
> }
> 
> WOQLQuery.prototype.read_object = WOQLQuery.prototype.read_document
> ```

Oh you are talking about the read_object yes it is already there but do we need to rename it as well ?

**Comment by Neelterminusdb** [comment]
I see that in #75 gavin has referenced it as delete_document so i will go with this name for now

**Comment by spl** [comment]
> Oh you are talking about the read_object yes it is already there but do we need to rename it as well ?

I don't know. I'm always for consistent naming, and I see `read_object` throughout the code here and `ReadDocument` in the schema, so, since we're changing things, it makes sense to me to rename, as long as we're not also breaking things.

**Comment by spl** [comment]
> I see that in #75 gavin has referenced it as delete_document so i will go with this name for now

Yep, so you can fix #75 and #78 in this PR.

**Comment by Neelterminusdb** [comment]
Oh okay i will create a new function called as read_document and depreciate the old one in documentation

**Comment by spl** [comment]
See <https://github.com/terminusdb/terminusdb-client-python/issues/267#issuecomment-983383998>.

File: lib/query/woqlQuery.js [hunk 1]
```diff
@@ -18,6 +18,57 @@ WOQLQuery.prototype.read_object = function(IRI, OutputVar, Format) {
     return this.wform(Format)
 }
 
+WOQLQuery.prototype.read_document = function(IRI, OutputVar, Format) {
+    //if (IRI && IRI == 'args') return ['document_uri', 'document']
```
Comment (spl) [inline lib/query/woqlQuery.js:22]: Remove comment.

File: lib/query/woqlQuery.js [hunk 2]
```diff
@@ -18,6 +18,57 @@ WOQLQuery.prototype.read_object = function(IRI, OutputVar, Format) {
...
+    if (this.cursor['@type']) this.wrapCursorWithAnd()
+    this.cursor['@type'] = 'ReadDocument'
+    this.cursor['identifier'] = this.cleanNodeValue(IRI)
+    this.cursor['document'] = this.expandValueVariable(OutputVar)
+    return this.wform(Format)
+}
+
+WOQLQuery.prototype.insert_document = function(docjson, IRI) {
+    //if (IRI && IRI == 'args') return ['document_uri', 'document']
```
Comment (spl) [inline lib/query/woqlQuery.js:31]: Remove comment.

File: lib/query/woqlQuery.js [hunk 3]
```diff
@@ -18,6 +18,57 @@ WOQLQuery.prototype.read_object = function(IRI, OutputVar, Format) {
...
+    if (this.cursor['@type']) this.wrapCursorWithAnd()
+    this.cursor['@type'] = 'InsertDocument'
+    if(typeof IRI !== 'undefined') this.cursor['identifier'] = this.cleanNodeValue(IRI)
+
+    let doc;
```
Comment (spl) [inline lib/query/woqlQuery.js:36]: Instead of declaring `doc` here, can you just do the assignment to `this.cursor['document']` directly in each block of the `if`/`else`?

File: lib/query/woqlQuery.js [hunk 4]
```diff
@@ -18,6 +18,57 @@ WOQLQuery.prototype.read_object = function(IRI, OutputVar, Format) {
...
+    } else {
+        doc = docjson;
+    }
+    
+    this.cursor['document'] = doc;
+    return this.updated()
+}
+
+WOQLQuery.prototype.update_document = function(docjson, IRI) {
+    //if (IRI && IRI == 'args') return ['document_uri', 'document']
```
Comment (spl) [inline lib/query/woqlQuery.js:48]: Remove comment.

File: lib/query/woqlQuery.js [hunk 5]
```diff
@@ -18,6 +18,57 @@ WOQLQuery.prototype.read_object = function(IRI, OutputVar, Format) {
...
+    if (this.cursor['@type']) this.wrapCursorWithAnd()
+    this.cursor['@type'] = 'UpdateDocument'
+    if(typeof IRI !== 'undefined') this.cursor['identifier'] = this.cleanNodeValue(IRI)
+
+    let doc;
```
Comment (spl) [inline lib/query/woqlQuery.js:53]: See comment above about assigning `this.cursor['document']` directly.

File: lib/query/woqlQuery.js [hunk 6]
```diff
@@ -18,6 +18,57 @@ WOQLQuery.prototype.read_object = function(IRI, OutputVar, Format) {
...
+    } else {
+        doc = docjson;
+    }
+
+    this.cursor['document'] = doc;
+    return this.updated()
+}
+
+WOQLQuery.prototype.delete_document = function(IRI) {
+    //if (IRI && IRI == 'args') return ['document_uri', 'document']
```
Comment (spl) [inline lib/query/woqlQuery.js:65]: Remove comment.

File: lib/query/woqlQuery.js [hunk 7]
```diff
@@ -18,6 +18,57 @@ WOQLQuery.prototype.read_object = function(IRI, OutputVar, Format) {
     return this.wform(Format)
 }
 
+WOQLQuery.prototype.read_document = function(IRI, OutputVar, Format) {
```
Comment (spl) [inline lib/query/woqlQuery.js:21]: The definition of `WOQLQuery.prototype.read_object` no longer works, so, in the goal of keeping things working and compatible, can you delete the definition and add this?

```js
WOQLQuery.prototype.read_object = WOQLQuery.prototype.read_document
```

For clarity, that should probably go after the `WOQLQuery.prototype.read_document` definition.

File: lib/woql.js [hunk 8]
```diff
@@ -92,17 +92,62 @@ WOQL.and = function(...subqueries) {
 
 
 /**
- * Read a node identified by an IRI as a JSON-LD document
+ * [Instead use read_document] Read a node identified by an IRI as a JSON-LD document
```
Comment (spl) [inline lib/woql.js:95]: Rather than add this, can you [add a message to `@deprecated`](https://jsdoc.app/tags-deprecated.html)?

File: lib/woql.js [hunk 9]
```diff
@@ -92,17 +92,62 @@ WOQL.and = function(...subqueries) {
...
+ */
+
+ WOQL.read_document = function(IRI, output, formatObj) {
+    return new WOQLQuery().read_document(IRI, output, formatObj)
+}
+
+/**
+ * Insert a document in the graph.
+ * @param {object} docjson -  The document to insert. Must either have an '@id' or have a class specified key.
+ * @param {string} [IRI] - An optional returned identifier specifying the documentation location.
```
Comment (spl) [inline lib/woql.js:122]: `An optional identifier specifying the document location.` I realize that this is wrong in the `woql.json`.

File: lib/woql.js [hunk 10]
```diff
@@ -92,17 +92,62 @@ WOQL.and = function(...subqueries) {
...
+ */
+
+WOQL.insert_document = function(docjson, IRI) {
+    return new WOQLQuery().insert_document(docjson, IRI)
+}
+
+/**
+ * Update a document identified by an IRI
+ * @param {object} docjson -  The document to update. Must either have an '@id' or have a class specified key.
+ * @param {string} [IRI] - An optional returned identifier specifying the documentation location.
```
Comment (spl) [inline lib/woql.js:133]: `An optional identifier specifying the document location.`

**Review by spl — CHANGES_REQUESTED** [review]
I don't suppose we have any tests for things like this, do we? Otherwise, there are just a few simple changes.

File: lib/query/woqlQuery.js (hunk 3 above)
Comment (Neelterminusdb) [reply lib/query/woqlQuery.js:36]: Ohh didn't look it that way

File: lib/query/woqlQuery.js (hunk 7 above)
Comment (Neelterminusdb) [reply lib/query/woqlQuery.js:21]: Rather than adding this here i think it would be better if i add this 
```
return new WOQLQuery().read_document(IRI, output, formatObj)
```
in here
https://github.com/terminusdb/terminusdb-client-js/blob/6d56272b37bfb5937017a88e491415ded25cebbf/lib/woql.js#L104

File: lib/woql.js (hunk 8 above)
Comment (Neelterminusdb) [reply lib/woql.js:95]: I have added it but it was not adding the text after the @deprecated so i added the tag and wrote the line here

File: lib/query/woqlQuery.js (hunk 7 above)
Comment (spl) [reply lib/query/woqlQuery.js:21]: Okay, but isn't `WOQLQuery.prototype.read_object` still wrong? We don't have `ReadObject` anymore.

File: lib/woql.js (hunk 8 above)
Comment (spl) [reply lib/woql.js:95]: I see! Fine then.

File: lib/query/woqlQuery.js (hunk 7 above)
Comment (Neelterminusdb) [reply lib/query/woqlQuery.js:21]: Yup so should i just remove it 😅

Comment (spl) [reply lib/query/woqlQuery.js:12]: Yep, just remove it. I confirmed with @Francesca-Bit that it's no longer accessible.

File: lib/woql.js (hunk 8 above)
Comment (spl) [reply lib/woql.js:95]: I learned from @Francesca-Bit that you can [`@link`](https://jsdoc.app/tags-inline-link.html) another name. So I suggest removing all documentation for `read_object` and adding something like this:

```
/**
 * Use {@link WOQL.read_document} instead.
 * @deprecated
 */
```

Just check the link to make sure it's correct. I haven't tested it.

**Review by spl — CHANGES_REQUESTED** [review]

**Review by spl — APPROVED** [review]
Thanks for adding tests!

**Comment by Neelterminusdb** [comment]
Thank you so much @spl for the detailed review of the PR  😄
